profiles: dev

server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/topic2?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

logging:
  level: debug

topic:
  key: D239S1ODL5N4
